### ISSUE TITLE
Issue 5

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test3#5]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x79ff3b4174e80c391b99057c9803857e50ea2e7febb25dd2640b89929efa670c](https://ropsten.etherscan.io/tx/0x79ff3b4174e80c391b99057c9803857e50ea2e7febb25dd2640b89929efa670c)
