### ISSUE TITLE
test image generation

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test3#6]
some

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x69587f923571407f901ea433626dcf3ae52959d2d890077cdf97de3de1ed0da0](https://ropsten.etherscan.io/tx/0x69587f923571407f901ea433626dcf3ae52959d2d890077cdf97de3de1ed0da0)
