### ISSUE TITLE
issue 7

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test3#7]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x7f18c19ba7e5b49735b4193ff4d23bcdce0bda4f96a6338c8b6705545dbd4b92](https://ropsten.etherscan.io/tx/0x7f18c19ba7e5b49735b4193ff4d23bcdce0bda4f96a6338c8b6705545dbd4b92)
