### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test3#8]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0xdd72beb57c62f282fe4fd6ede1c608ed8f3d4769a0f45ea47a0c5fc6cf774464](https://ropsten.etherscan.io/tx/0xdd72beb57c62f282fe4fd6ede1c608ed8f3d4769a0f45ea47a0c5fc6cf774464)

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0xb1da58608e0e11661f7b887188da4c82574b8a24c57b2882bdfb24f573709069](https://ropsten.etherscan.io/tx/0xb1da58608e0e11661f7b887188da4c82574b8a24c57b2882bdfb24f573709069)

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0xfb78bd4b76b7da4e0a78293650635acc956f28de607e462fa2e9fb03adf804e9](https://ropsten.etherscan.io/tx/0xfb78bd4b76b7da4e0a78293650635acc956f28de607e462fa2e9fb03adf804e9)

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0xdd72beb57c62f282fe4fd6ede1c608ed8f3d4769a0f45ea47a0c5fc6cf774464](https://ropsten.etherscan.io/tx/0xdd72beb57c62f282fe4fd6ede1c608ed8f3d4769a0f45ea47a0c5fc6cf774464)

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x1f2f6e06e947c33c0918ab67acf403e7fc323f61777f71582dcaf015441fae16](https://ropsten.etherscan.io/tx/0x1f2f6e06e947c33c0918ab67acf403e7fc323f61777f71582dcaf015441fae16)

**Comment by siphiuel** [comment]
new comment
