### ISSUE TITLE
revoke

### ISSUE THREAD

**Issue by siphiuel** [siphiuel/ob-test3#9]

**Comment by commiteth** [comment]
![Contract deploying](http://194.44.239.202:3003/img/deploying_contract.png)
Transaction: [0x3acaad56a58921396efe2cdba78d2e533d09795712e75d0e987915bd3bad34d5](https://ropsten.etherscan.io/tx/0x3acaad56a58921396efe2cdba78d2e533d09795712e75d0e987915bd3bad34d5)
